spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: orders
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
            - id: notification-instance
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/instance
              filters:
                - RewritePath=/api/notifications/instance,/instance
            - id: notifications
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications
